name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  with_features:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        toolchain:
          - 1.85
          - stable
          - beta
          - nightly
        include:
          - feature: simulation,sqlite
        exclude:
          - os: windows
            toolchain: nightly
    env:
      __MAKE_DEFAULT_TOOLCHAIN__: ${{ matrix.toolchain }}
    steps:
      - uses: actions/checkout@v4
      - name: Show environment variables
        run: env
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose --all --features ${{ matrix.feature }}
      - run: cargo test --verbose --all --features ${{ matrix.feature }}
  build_docs:
    runs-on: ubuntu-latest
    env:
        RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - run: rustup default nightly
      - run: cargo install cargo-docs-rs
      - run: cargo docs-rs -p wb-cache

